[build]
target = "index.html"
release = true
dist = "dist"
public_url = "/"

[watch]
# Paths to watch. The `build.target`'s parent folder is watched by default.
watch = [
  "src",
  "../shared/src",
  "index.html",
  "input.css",
  "tailwind.config.js",
]
ignore = ["dist", "node_modules"]

[serve]
address = "0.0.0.0"
port = 8081
open = false
fallback_service = "index.html"

# [[proxy]]
# rewrite = "/lobby/"
# backend = "http://backend:8080/lobby/"
#
# [[proxy]]
# rewrite = "/player/"
# backend = "http://backend:8080/player/"
#
# [[proxy]]
# rewrite = "/kanji/"
# backend = "http://backend:8080/kanji/"
#
# [[proxy]]
# rewrite = "/new_kanji/"
# backend = "http://backend:8080/new_kanji/"
#
# [[proxy]]
# rewrite = "/check_word/"
# backend = "http://backend:8080/check_word/"
