[package]
name = "my_project"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
csv = "1.1"
rand = "0.8"
tokio = { version = "1.43.0", features = ["full"] }
axum = "0.8.1"
tower-http = { version = "0.6.2", features = ["full"] }
