services:
  db:
    image: docker.io/library/postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kanji_network

  app:
    build:
      context: .
      dockerfile: Dockerfile # Production
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "8080:8080"
    networks:
      - kanji_network
    volumes:
      - ./data:/usr/local/data:ro

networks:
  kanji_network:
    driver: bridge

volumes:
  postgres_data:
