services:
  db:
    image: docker.io/library/postgres:15
    restart: always
    environment:
      POSTGRES_USER: kanji 
      POSTGRES_PASSWORD: kanji
      POSTGRES_DB: kanji_game
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kanji_network

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev # For development
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://kanji:kanji@db:5432/kanji_game
      HOST: 0.0.0.0
      PORT: 8080
      RUST_LOG: debug # More verbose logging
      PRODUCTION: 0 # 0 for Development mode
    ports:
      - "8080:8080"
    networks:
      - kanji_network
    volumes:
      - ./data:/usr/local/data:ro

networks:
  kanji_network:
    driver: bridge

volumes:
  postgres_data:
